### ISSUE TITLE
Kelp always use a thread

### ISSUE THREAD

**Issue by CPagador** [gautam8404/kelp#2]
I test engines with ponder off and single core, to get the largest quantity of games with my PC (16 threads). Kelp 0.12.0 always grab a thread, wether it is his turn or not. It does not seem to be pondering, but Kelp uses this thread at all times anyway. Is there a way that you can fix this?

PC: R7 5700G 
OS: W10 x64

**Comment by gautam8404** [comment]
Hey @CPagador 

Kelp uses an extra thread to listen for inputs all the times which allow commands to be executed even when kelp is searching 

Without this there's no way to stop kelp search through external input from gui or user

There's ofc single threaded implementations but I found it really janky to get stdio within search which is why I opted for this (there are probably better ways which i am not aware of)

Afaik input threads are allowed to run all the times in UCI as long as they're not being used for search or any other engine function

I hope this answers your issue

**Comment by CPagador** [comment]
I understand, I guess you can request help about this on talkchess forum. There are many chess engines authors who discuss about many issues like this.

I included your engine on my tournament anyway. You can find it here:

https://talkchess.com/forum3/viewtopic.php?t=83473

Kelp plays in the Promotion League 9. I will post the results tomorrow.

**Comment by gautam8404** [comment]
Thanks a lot for including kelp in your tournament!

And thanks for recc, I'll surely ask on talkchess  when I start working on it again, kelp was pretty much my first rust project and chess engine there are many things I've done wrong and many things I want to improve
